"""update table field

Revision ID: 56f2c70cf0aa
Revises: 88890a049269
Create Date: 2025-06-04 16:35:55.776740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f2c70cf0aa'
down_revision: Union[str, None] = '88890a049269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('platforms', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'description')
    op.drop_column('conversations', 'is_active')
    # ### end Alembic commands ###
