"""update

Revision ID: 9d0eb13ee0c9
Revises: 25f093a92447
Create Date: 2025-06-05 17:01:57.003200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0eb13ee0c9'
down_revision: Union[str, None] = '25f093a92447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('conversation_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'conversations', ['conversation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_column('conversations', 'conversation_id')
    # ### end Alembic commands ###
